name: CI

on:
  push:
    branches:
      - master

jobs:
  generate-dependency-graph:
      name: Generate Dependency Graph
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Checkout project sources
          uses: actions/checkout@v2
        
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2
        - name: Run build with Gradle Wrapper
          run: ./gradlew build

        - name: Setup Graphviz
          uses: ts-graphviz/setup-graphviz@v1

        - name: Generate Dependency Graph
          run: ./gradlew pdg

        - name: Commmit
          run: |
            git config --local user.email 'action@github.com'
            git config --local user.name 'GitHub Action'
            git diff --quiet && git diff --staged --quiet || git commit -am 'Update dependency graph'

        - name: Push
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
